# Generated by Django 6.0.4 on 2026-04-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_appointment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='user',
            new_name='patient',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='customer_name',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
