# Generated by Django 6.0.4 on 2026-04-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_appointment_price_at_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('FACIAL', 'Facial Treatments'), ('ZO', 'ZO Professional Facial'), ('DOCTOR', 'Doctors Procedure'), ('LASER', 'Laser Gynecology'), ('ADDON', 'Add-On Treatment')], default='FACIAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
