# Generated by Django 6.0.4 on 2026-04-27 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_alter_service_category_alter_service_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='duration_minutes',
        ),
    ]
