# Generated by Django 6.0.4 on 2026-04-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_remove_service_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='has_addon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='location',
            field=models.CharField(choices=[('Baseline', 'Shields Aesthetic Clinic - Baseline Center'), ('CebuDoc', 'OB-Gynecology Clinic - Cebu Doctors Hospital')], default='Baseline', max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='specialist',
            field=models.CharField(default='Dr. Rass Shields Pimentel', max_length=255),
        ),
    ]
