# Generated by Django 6.0.4 on 2026-05-02 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_appointment_reference_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('date', 'time')},
        ),
    ]
