# Generated by Django 6.0.4 on 2026-05-03 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_appointment_addon_service_alter_appointment_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
    ]
