# Generated by Django 6.0.4 on 2026-05-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_notes',
            field=models.TextField(blank=True, help_text='Private notes for doctor only', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_notes_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_notes_updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
