# Generated by Django 6.0.4 on 2026-05-13 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0015_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='doctor_id',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Philippine mobile number in the format 09XXXXXXXXX.', regex='^09\\d{9}$')]),
        ),
    ]
