# Generated by Django 6.0.4 on 2026-05-14 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0016_profile_doctor_id_profile_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointment',
            table='appointments',
        ),
        migrations.AlterModelTable(
            name='patientprofileaudit',
            table='patient_profile_audits',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='user_profiles',
        ),
        migrations.AlterModelTable(
            name='service',
            table='services',
        ),
    ]
